apiVersion: v1
kind: ServiceAccount
metadata:
  name: todolist-app
  namespace: todolist
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: todolist-app
  namespace: todolist
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: todolist-app
  namespace: todolist
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: todolist-app
subjects:
  - kind: ServiceAccount
    name: todolist-app
    namespace: todolist