apiVersion: v1
kind: Secret
metadata:
  name: todolist-secrets
  namespace: todolist
type: Opaque
stringData:
  DB_PASSWORD: "todolist123"
  SESSION_KEY: "dev-only-insecure-session-key"
  ADMIN_USER: "admin"
  ADMIN_PASSWORD: "admin"
  CLEANUP_TOKEN: "local-cleanup-token-123"