apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todolist.fullname" . }}
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.config.appName | quote }}
  APP_PORT: {{ .Values.config.appPort | quote }}
  APP_COLOR: {{ .Values.config.appColor | quote }}
  DB_HOST: {{ if .Values.postgresql.enabled }}{{ include "todolist.postgresServiceName" . | quote }}{{ else }}{{ .Values.config.dbHost | quote }}{{ end }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
