{{- if .Values.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "todolist.fullname" . }}
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.storeName }}
    kind: {{ .Values.externalSecret.storeKind }}
  target:
    name: {{ include "todolist.secretName" . }}
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.externalSecret.dbSecretArn }}
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.dbSecretArn }}
        property: password
    {{- if .Values.externalSecret.appSecretArn }}
    - secretKey: SESSION_KEY
      remoteRef:
        key: {{ .Values.externalSecret.appSecretArn }}
        property: SESSION_KEY
    - secretKey: ADMIN_USER
      remoteRef:
        key: {{ .Values.externalSecret.appSecretArn }}
        property: ADMIN_USER
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.appSecretArn }}
        property: ADMIN_PASSWORD
    - secretKey: CLEANUP_TOKEN
      remoteRef:
        key: {{ .Values.externalSecret.appSecretArn }}
        property: CLEANUP_TOKEN
    {{- end }}
{{- end }}
