{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "todolist.postgresClaimName" . }}
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todolist.postgresServiceName" . }}
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "todolist.postgresSelectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todolist.postgresServiceName" . }}
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "todolist.postgresSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "todolist.postgresSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgresql.image }}
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.config.dbName | quote }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "todolist.secretName" . }}
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "todolist.secretName" . }}
                  key: DB_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "todolist.postgresClaimName" . }}
{{- end }}
